name: CxONE Scan 
on: 
  push:
    branches:
      - main
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: "CSVintoCxONE"
          cx_tenant: "cec_emea_test_emanuel_ribeiro"
          base_uri: "https://eu.ast.checkmarx.net"
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.SECRET }}
          additional_params: --file-filter !readme --report-format sarif --output-name results
          #cx_apikey: ${{ secrets.APIKEY }}
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
